export const specialtyEtoB = {
    'Internal Medicine': 'ইন্টারনাল মেডিসিন',
    'Cardiology': 'হৃদরোগ',
    'Nephrology': 'কিডনি',
    'Respiratory Medicine': 'ফুসফুস',
    'Rheumatology': 'বাতরোগ',
    'Gastroenterology': 'পরিপাকতন্ত্র',
    'Hepatology': 'লিভার',
    'Neurology': 'স্নায়ুরোগ',
    'Oncology': 'ক্যান্সার',
    'Hematology': 'রক্তরোগ',
    'Endocrinology': 'হরমোন',
    'Dermatology & Venereology': 'চর্ম ও যৌনরোগ',
    'Pediatrics': 'শিশুরোগ',
    'Psychiatry': 'মনোরোগ',
    'Physical Medicine & Rehabilitation': 'ফিজিক্যাল মেডিসিন',
    'Aesthetic Dermatology': 'এস্থেটিক ডার্মাটোলজি',

    'General Surgery': 'জেনারেল সার্জারি',
    'Orthopedic Surgery': 'অর্থোপেডিক সার্জারি',
    'Neurosurgery': 'স্নায়ু সার্জারি',
    'Gynecology & Obstetrics': 'স্ত্রীরোগ ও প্রসূতি',
    'ENT & Head Neck Surgery': 'নাক, কান ও গলা',
    'Ophthalmology': 'চক্ষু',
    'Oral & Dental Surgery': 'ডেন্টাল সার্জারি',
    'Urology': 'মুত্ররোগ সার্জারি',
    'Colorectal Surgery': 'কোলন, রেকটাম সার্জারি',
    'Pediatric Surgery': 'শিশুরোগ সার্জারি',
    'Vascular Surgery': 'রক্তনালী সার্জারি',
};